#
# Leo Cache
#
language: erlang
script: "make && make eunit"
notifications:
  email: false
otp_release:
  - 18.3
  - 19.3
  - 20.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check
